### ISSUE TITLE
Request for additional table

### ISSUE THREAD

**Issue by BakerJL75** [jfcardinal/ORA-Tables#1]
I would love a table of US abbreviations that use the traditional abbreviation rather than the 2 letter postal code as shown on Wikipedia.  [Wikipedia](https://simple.wikipedia.org/wiki/List_of_U.S._states_by_traditional_abbreviation). Thanks!

**Comment by jfcardinal** [comment]
This should probably be discussed on the ORA-L list to see if other users would benefit from adding this table to ORA.

The Wikipedia table has two and sometimes three entries for some states, i.e., Idaho has a "traditional" abbreviation ("Idaho") and two other abbreviations ("Id." and "Ida."). That makes me question how standard the traditional abbreviations were/are. Is it a good idea to use them now that the two-letter codes have been standardized and adopted?

**Comment by BakerJL75** [comment]
I will repost there in a few minutes.

Your help page said " The contents of the tables listed above are
maintained on GitHub. You may review them and suggest changes via this page:
https://github.com/jfcardinal/ORA-Tables" so that's why I posted at GitHub.

**Comment by jfcardinal** [comment]
No problem on posting here. The comment of mine you quoted was trying to refer to changes to the existing tables, not the addition of tables.
